[package]
name = "rust-agent"
version = "0.1.0"
authors = ["Jonas Hahn <jonas.hahn@datenhahn.de>"]

[dependencies]

serde = "1.0"
serde_derive = "1.0"
toml = "0.4.2"
subprocess = "0.1.13"
reqwest = "0.8.6"